// I-Ching-derived names for the 64 gates. These are the traditional HD names,
// not direct I-Ching titles, but close. Used for display on /chart.

export const GATE_NAMES: Record<number, string> = {
  1: 'Self-Expression',
  2: 'Direction',
  3: 'Ordering',
  4: 'Formulization',
  5: 'Fixed Patterns',
  6: 'Friction',
  7: 'The Role of the Self',
  8: 'Contribution',
  9: 'Focus',
  10: 'Behavior of the Self',
  11: 'Ideas',
  12: 'Caution',
  13: 'The Listener',
  14: 'Power Skills',
  15: 'Extremes',
  16: 'Skills',
  17: 'Opinions',
  18: 'Correction',
  19: 'Wanting',
  20: 'The Now',
  21: 'The Hunter / Huntress',
  22: 'Openness',
  23: 'Assimilation',
  24: 'Rationalizing',
  25: 'Innocence',
  26: 'The Egoist',
  27: 'Caring',
  28: 'The Game Player',
  29: 'Saying Yes',
  30: 'Desires',
  31: 'Influence',
  32: 'Continuity',
  33: 'Retreat',
  34: 'Power',
  35: 'Change',
  36: 'Crisis',
  37: 'Friendship',
  38: 'The Fighter',
  39: 'Provocation',
  40: 'Aloneness',
  41: 'Imagination',
  42: 'Growth',
  43: 'Insight',
  44: 'Coming to Meet',
  45: 'The Gatherer',
  46: 'Love of the Body',
  47: 'Realization',
  48: 'Depth',
  49: 'Revolution',
  50: 'Values',
  51: 'Shock',
  52: 'Stillness',
  53: 'Beginnings',
  54: 'Ambition',
  55: 'Spirit',
  56: 'The Storyteller',
  57: 'Intuitive Clarity',
  58: 'Joy',
  59: 'Sexuality',
  60: 'Acceptance',
  61: 'Mystery',
  62: 'Detail',
  63: 'Doubt',
  64: 'Confusion',
};

export function gateName(n: number): string {
  return GATE_NAMES[n] ?? `Gate ${n}`;
}
