import type { Metadata } from 'next';
import { Inter, DM_Serif_Display } from 'next/font/google';
import './globals.css';
import TabBar from '@/components/TabBar';
import InstallHint from '@/components/InstallHint';
import PixelCreatures from '@/components/PixelCreatures';
import OfflineBanner from '@/components/OfflineBanner';
import RegisterServiceWorker from '@/components/RegisterServiceWorker';

const sans = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-sans',
});

const serif = DM_Serif_Display({
  subsets: ['latin'],
  weight: ['400'],
  display: 'swap',
  variable: '--font-serif',
});

export const metadata: Metadata = {
  title: {
    default: 'Liraydhas',
    template: '%s · Liraydhas',
  },
  description: 'A daily reading of the sky, and your design.',
  applicationName: 'Liraydhas',
  appleWebApp: {
    capable: true,
    title: 'Liraydhas',
    statusBarStyle: 'black-translucent',
  },
  formatDetection: { telephone: false },
  // Icons are now generated by app/icon.tsx (favicon, 32×32 PNG) and
  // app/apple-icon.tsx (apple-touch-icon, 180×180 PNG) via Next.js
  // ImageResponse. The old SVGs in /public stay as web-manifest fallbacks
  // (those still serve from manifest.ts), but iOS now gets a real PNG
  // for the home-screen icon instead of silently falling back to a
  // screenshot.
};

export const viewport = {
  width: 'device-width',
  initialScale: 1,
  themeColor: '#0a0a0a',
  maximumScale: 1,
  viewportFit: 'cover' as const,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${sans.variable} ${serif.variable}`}>
      <body>
        <div className="grain" aria-hidden />
        <OfflineBanner />
        {children}
        <PixelCreatures />
        <TabBar />
        <InstallHint />
        <RegisterServiceWorker />
      </body>
    </html>
  );
}
