import { NextResponse } from 'next/server';
import webpush from 'web-push';
import { listSubs, removeSub, toWebPush, DEFAULT_PREFS } from '@/lib/pushStore';
import { sendApns, getApnsClient } from '@/lib/apnsClient';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

/**
 * Scheduled by Vercel Cron (see vercel.json). Fires once a day at the
 * configured hour and pushes a quiet "your reading is ready" notification
 * to every subscribed device.
 *
 * Security: Vercel Cron requests carry an `Authorization: Bearer <CRON_SECRET>`
 * header so this route can't be invoked by anyone with the URL. The secret
 * is auto-generated by Vercel and made available as the CRON_SECRET env
 * var; we just need to verify it matches.
 *
 * If you trigger this manually (curl, Postman, a test), include the same
 * header.
 */
export async function GET(req: Request) {
  // Auth check — Vercel Cron sends Bearer CRON_SECRET. Reject everyone else.
  const secret = process.env.CRON_SECRET;
  if (secret) {
    const auth = req.headers.get('authorization');
    if (auth !== `Bearer ${secret}`) {
      return NextResponse.json({ error: 'unauthorized' }, { status: 401 });
    }
  } else {
    // No secret configured — refuse to send so an open cron endpoint
    // doesn't become a notification spammer.
    return NextResponse.json(
      { error: 'CRON_SECRET not configured — refusing to send' },
      { status: 501 },
    );
  }

  // Configure web-push if VAPID is set (web subscribers will be skipped
  // when it isn't). APNs is configured lazily by getApnsClient(); native
  // subscribers are skipped when its env vars are missing.
  const pub = process.env.VAPID_PUBLIC_KEY;
  const priv = process.env.VAPID_PRIVATE_KEY;
  const subject = process.env.VAPID_SUBJECT;
  const hasWeb = !!(pub && priv && subject);
  const hasApns = !!getApnsClient();
  if (!hasWeb && !hasApns) {
    return NextResponse.json(
      { error: 'no push provider configured (need VAPID_* or APNS_*)' },
      { status: 501 },
    );
  }
  if (hasWeb) webpush.setVapidDetails(subject as string, pub as string, priv as string);

  const subs = await listSubs();
  // Cron runs hourly (vercel.json). Each subscriber gets the ping when
  // their LOCAL hour matches their preferred hour. We compute "their
  // current local hour" as (UTC hour + tzOffsetMin/60) mod 24, and
  // their local day-of-week by shifting UTC time by tzOffsetMin.
  const now = new Date();
  const utcHour = now.getUTCHours();

  /**
   * Pick what to send for one subscriber, or null to skip them this hour.
   *
   * Priority: weekly (Monday only) wins over daily on the day they
   * collide, so a Monday-morning subscriber gets the week-behind digest
   * once a week instead of a duplicate ping.
   */
  function chooseSurface(s: typeof subs[number]): { body: string; url: string } | null {
    const p = s.prefs ?? DEFAULT_PREFS;
    const localHour = ((utcHour + Math.floor(p.tzOffsetMin / 60)) % 24 + 24) % 24;
    if (localHour !== p.hourLocal) return null;
    // Local day-of-week from a shifted Date. 0 = Sun, 1 = Mon, ..., 6 = Sat.
    const local = new Date(now.getTime() + p.tzOffsetMin * 60_000);
    const localDow = local.getUTCDay();
    if (p.types.weekly && localDow === 1) {
      return { body: 'the week behind — open when you have a minute.', url: '/today' };
    }
    if (p.types.daily) {
      return { body: "today's reading is ready.", url: '/today' };
    }
    // No matching surface — user has anniversary type only, which is
    // handled by client-side local notifications (Capacitor), not by
    // this server-side cron.
    return null;
  }

  // Resolve each subscriber to a (sub, surface) pair, drop nulls.
  const eligible = subs
    .map((s) => ({ sub: s, surface: chooseSurface(s) }))
    .filter((x): x is { sub: typeof subs[number]; surface: { body: string; url: string } } => x.surface !== null);

  let sent = 0;
  let failed = 0;
  let pruned = 0;
  await Promise.all(
    eligible.map(async ({ sub: s, surface }) => {
      const payload = JSON.stringify({
        title: 'Liraydhas',
        body: surface.body,
        url: surface.url,
      });
      try {
        if (s.kind === 'apns') {
          if (!hasApns) return;
          await sendApns({
            token: s.token,
            title: 'Liraydhas',
            body: surface.body,
            url: surface.url,
          });
          sent++;
        } else {
          if (!hasWeb) return;
          await webpush.sendNotification(toWebPush(s), payload);
          sent++;
        }
      } catch (e: unknown) {
        failed++;
        // Detect dead subscriptions on both transports.
        const msg = e instanceof Error ? e.message : String(e);
        const isWebDead = /statusCode.{0,5}(404|410)/.test(msg);
        const isApnsDead = /BadDeviceToken|Unregistered|410|invalid token/i.test(msg);
        if (isWebDead || isApnsDead) {
          await removeSub(s.kind === 'apns' ? s.token : s.endpoint);
          pruned++;
        } else {
          console.error('[cron] send failed:', e);
        }
      }
    }),
  );
  return NextResponse.json({
    ranAt: new Date().toISOString(),
    subscribers: subs.length,
    eligible: eligible.length,
    sent,
    failed,
    pruned,
  });
}
