import { NextResponse } from 'next/server';
import webpush from 'web-push';
import { listSubs, removeSub, toWebPush, DEFAULT_PREFS } from '@/lib/pushStore';
import { sendApns, getApnsClient } from '@/lib/apnsClient';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

/**
 * Scheduled by Vercel Cron (see vercel.json). Fires once a day at the
 * configured hour and pushes a quiet "your reading is ready" notification
 * to every subscribed device.
 *
 * Security: Vercel Cron requests carry an `Authorization: Bearer <CRON_SECRET>`
 * header so this route can't be invoked by anyone with the URL. The secret
 * is auto-generated by Vercel and made available as the CRON_SECRET env
 * var; we just need to verify it matches.
 *
 * If you trigger this manually (curl, Postman, a test), include the same
 * header.
 */
export async function GET(req: Request) {
  // Auth check — Vercel Cron sends Bearer CRON_SECRET. Reject everyone else.
  const secret = process.env.CRON_SECRET;
  if (secret) {
    const auth = req.headers.get('authorization');
    if (auth !== `Bearer ${secret}`) {
      return NextResponse.json({ error: 'unauthorized' }, { status: 401 });
    }
  } else {
    // No secret configured — refuse to send so an open cron endpoint
    // doesn't become a notification spammer.
    return NextResponse.json(
      { error: 'CRON_SECRET not configured — refusing to send' },
      { status: 501 },
    );
  }

  // Configure web-push if VAPID is set (web subscribers will be skipped
  // when it isn't). APNs is configured lazily by getApnsClient(); native
  // subscribers are skipped when its env vars are missing.
  const pub = process.env.VAPID_PUBLIC_KEY;
  const priv = process.env.VAPID_PRIVATE_KEY;
  const subject = process.env.VAPID_SUBJECT;
  const hasWeb = !!(pub && priv && subject);
  const hasApns = !!getApnsClient();
  if (!hasWeb && !hasApns) {
    return NextResponse.json(
      { error: 'no push provider configured (need VAPID_* or APNS_*)' },
      { status: 501 },
    );
  }
  if (hasWeb) webpush.setVapidDetails(subject as string, pub as string, priv as string);

  const payload = JSON.stringify({
    title: 'Liraydhas',
    body: "today's reading is ready.",
    url: '/today',
  });

  const subs = await listSubs();
  // Cron runs hourly (vercel.json). Each subscriber gets the ping when
  // their LOCAL hour matches their preferred hour. We compute "their
  // current local hour" as (UTC hour + tzOffsetMin/60) mod 24.
  const now = new Date();
  const utcHour = now.getUTCHours();
  const eligible = subs.filter((s) => {
    const p = s.prefs ?? DEFAULT_PREFS;
    if (!p.types.daily) return false;
    const localHour = ((utcHour + Math.floor(p.tzOffsetMin / 60)) % 24 + 24) % 24;
    return localHour === p.hourLocal;
  });

  let sent = 0;
  let failed = 0;
  let pruned = 0;
  await Promise.all(
    eligible.map(async (s) => {
      try {
        if (s.kind === 'apns') {
          if (!hasApns) return;
          await sendApns({
            token: s.token,
            title: 'Liraydhas',
            body: "today's reading is ready.",
            url: '/today',
          });
          sent++;
        } else {
          if (!hasWeb) return;
          await webpush.sendNotification(toWebPush(s), payload);
          sent++;
        }
      } catch (e: unknown) {
        failed++;
        // Detect dead subscriptions on both transports.
        const msg = e instanceof Error ? e.message : String(e);
        const isWebDead = /statusCode.{0,5}(404|410)/.test(msg);
        const isApnsDead = /BadDeviceToken|Unregistered|410|invalid token/i.test(msg);
        if (isWebDead || isApnsDead) {
          await removeSub(s.kind === 'apns' ? s.token : s.endpoint);
          pruned++;
        } else {
          console.error('[cron] send failed:', e);
        }
      }
    }),
  );
  return NextResponse.json({
    ranAt: new Date().toISOString(),
    subscribers: subs.length,
    eligible: eligible.length,
    sent,
    failed,
    pruned,
  });
}
