import { NextResponse } from 'next/server';
import webpush from 'web-push';
import { listSubs, removeSub, toWebPush } from '@/lib/pushStore';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

/**
 * Scheduled by Vercel Cron (see vercel.json). Fires once a day at the
 * configured hour and pushes a quiet "your reading is ready" notification
 * to every subscribed device.
 *
 * Security: Vercel Cron requests carry an `Authorization: Bearer <CRON_SECRET>`
 * header so this route can't be invoked by anyone with the URL. The secret
 * is auto-generated by Vercel and made available as the CRON_SECRET env
 * var; we just need to verify it matches.
 *
 * If you trigger this manually (curl, Postman, a test), include the same
 * header.
 */
export async function GET(req: Request) {
  // Auth check — Vercel Cron sends Bearer CRON_SECRET. Reject everyone else.
  const secret = process.env.CRON_SECRET;
  if (secret) {
    const auth = req.headers.get('authorization');
    if (auth !== `Bearer ${secret}`) {
      return NextResponse.json({ error: 'unauthorized' }, { status: 401 });
    }
  } else {
    // No secret configured — refuse to send so an open cron endpoint
    // doesn't become a notification spammer.
    return NextResponse.json(
      { error: 'CRON_SECRET not configured — refusing to send' },
      { status: 501 },
    );
  }

  const pub = process.env.VAPID_PUBLIC_KEY;
  const priv = process.env.VAPID_PRIVATE_KEY;
  const subject = process.env.VAPID_SUBJECT;
  if (!pub || !priv || !subject) {
    return NextResponse.json(
      { error: 'VAPID not configured' },
      { status: 501 },
    );
  }
  webpush.setVapidDetails(subject, pub, priv);

  const payload = JSON.stringify({
    title: 'Liraydhas',
    body: "today's reading is ready.",
    url: '/today',
  });

  const subs = await listSubs();
  let sent = 0;
  let failed = 0;
  let pruned = 0;
  await Promise.all(
    subs.map(async (s) => {
      try {
        await webpush.sendNotification(toWebPush(s), payload);
        sent++;
      } catch (e: unknown) {
        failed++;
        // 404 / 410 = subscription is gone (user uninstalled the app,
        // revoked permission, etc.). Drop it from the store so we stop
        // hammering a dead endpoint.
        if (
          e instanceof Error &&
          /statusCode.{0,5}(404|410)/.test(e.message)
        ) {
          await removeSub(s.endpoint);
          pruned++;
        } else {
          console.error('[cron] send failed:', e);
        }
      }
    }),
  );
  return NextResponse.json({
    ranAt: new Date().toISOString(),
    subscribers: subs.length,
    sent,
    failed,
    pruned,
  });
}
